import * as React from 'react';
import { useState, useEffect } from 'react';
import Layout from '@/components/layout/Layout';
import WorldMap from '@/components/WorldMap';
import ArrowLink from '@/components/links/ArrowLink';
import ButtonLink from '@/components/links/ButtonLink';
import UnderlineLink from '@/components/links/UnderlineLink';
import UnstyledLink from '@/components/links/UnstyledLink';
import Seo from '@/components/Seo';
import BarChartTotalEmissions from '@/components/graphs/BarChartTotalEmissions';
import BarChartBudget from '@/components/graphs/BarChartBudget';
import Select from 'react-select';


const SectionKPIs = () => {
  return (
    <section className="bg-gray-100 py-10 my-10">
      <div className="container mx-auto px-8">
        <div className="max-w-3xl">
          <h3 className="text-2xl font-bold mb-2">Carbon bombs at a glance</h3>
          <div className="text-gray-500">Updated: 03/24/23</div>
        </div>
        <div className="flex flex-wrap -mx-4 mt-6">
          <div className="w-full sm:w-1/2 lg:w-1/4 px-4 mb-4">
            <div className="bg-white rounded-lg shadow flex flex-col items-stretch h-full p-6">
              <h3 className="text-5xl font-bold mb-1">425</h3>
              <div className="font-bold">CARBON BOMBS WORLDWIDE</div>
              <p className="mt-2">425 fossil fuel projects around the world will generate more than 1 gigatonne of CO2 emissions during their lifetime.</p>
            </div>
          </div>
          <div className="w-full sm:w-1/2 lg:w-1/4 px-4 mb-4">
            <div className="bg-white rounded-lg shadow flex flex-col items-stretch h-full p-6">
              <h3 className="text-5xl font-bold mb-1">x2</h3>
              <div className="font-bold">EXCEED 1.5°C CARBON BUDGET BY A FACTOR OF TWO</div>
              <p className="mt-2">The cumulated volume of emissions generated by the 425 projects alone is twice larger than the 1.5°C carbon budget.</p>
            </div>
          </div>
          <div className="w-full sm:w-1/2 lg:w-1/4 px-4 mb-4">
            <div className="bg-white rounded-lg shadow flex flex-col items-stretch h-full p-6">
              <h3 className="text-5xl font-bold mb-1">30</h3>
              <div className="font-bold">MAJOR COMPANIES AND BANKS</div>
              <p className="mt-2">are involved in the 425 projects.</p>
            </div>
          </div>
          <div className="w-full sm:w-1/2 lg:w-1/4 px-4 mb-4">
            <div className="bg-white rounded-lg shadow flex flex-col items-stretch h-full p-6">
              <h3 className="text-5xl font-bold mb-1">40%</h3>
              <div className="font-bold">HAVE NOT STARTED YET</div>
              <p className="mt-2">40% of carbon bombs had not started extraction in 2020.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

const CarbonBombInfo = () => {
  return (
    <section className="container my-10">
      <div className="text-center">
        <h2 className="text-2xl font-bold mb-4">What is a carbon bomb?</h2>
        <p>Carbon bombs are fossil fuel projects that generate massive amounts of CO2 emissions and are likely to significantly threaten the 1.5°C climate target.</p>
        <p className="mt-2">425 carbon bombs, spread across 28 countries, are likely to individually <b>generate more than one billion tons of CO2</b> over their lifetime.</p>
        <p className="mt-2">The full operation of these 425 carbon bombs will emit twice as much CO2 as would be required to stay below 1.5°C of global warming.</p>
        <p className="mt-2"><i>By 2020, 40% of these projects had not yet started.</i></p>
      </div>
    </section>
  );
}


const CarbonBombSection = ({ bombsData }) => {
  return (
    <div className="py-16">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className="relative">
            <BarChartBudget bombsData={bombsData} />
            {/* <img
              src="https://uploads-ssl.webflow.com/64206379a2bd1eb2474bc869/642334e16b604aefe233d247_WhatsApp%20Image%202023-03-26%20at%2017.15%202.png"
              className="w-full h-auto px-40"
              alt=""
              loading="lazy"
            /> */}
          </div>
          <div className="flex flex-col justify-center">
            <div className="mb-4">
              <h2 className="text-2xl font-bold" id="carbon-budget">
                425 carbon bombs over the globe are threatening our 1.5°C carbon budget
              </h2>
            </div>
            <p className="text-lg">
              In order to limit global warming to +1.5°C compared to the pre-industrial era, the cumulated global emissions must not exceed 420 to 580 gigatonnes of CO2.
              <br /><br />
              Yet, the cumulated emissions of the 425 carbon bombs amount to over 1180 gigatonnes of CO2, which would exceed the global 1.5°C carbon budget by a factor of two.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}


const TimeToActSection = ({ bombsData }) => {
  return (
    <div className="py-16">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className="flex flex-col justify-center">
            <div className="mb-4">
              <h2 className="text-2xl font-bold" id="time-to-act">
                It is still time to act
              </h2>
            </div>
            <p className="text-lg">
              40% of the 425 carbon bombs had not started extraction in 2020. Those 169 projects amount to one third of the carbon bombs’ cumulated emissions. It is still time to act in order to cancel them. There is also a way to limit the cumulated emissions of the 256 existing carbon bombs: stopping any further investments they could receive, in order to put them into a pathway of natural decline of their oil, gas, and coal outputs.
            </p>
          </div>
          <div className="relative">
            {/* <img
              src="https://uploads-ssl.webflow.com/64206379a2bd1eb2474bc869/64237250cd6ed9391d054996_WhatsApp%20Image%202023-03-28%20at%2021.39.22.jpeg"
              className="w-full h-auto px-40"
              alt=""
              loading="lazy"
            /> */}
            <BarChartTotalEmissions bombsData={bombsData} />
          </div>
        </div>
      </div>
    </div>
  );
}


const BanksSection = () => {
  return (
    <div className="py-16">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className="relative">
            <img
              src="https://uploads-ssl.webflow.com/64206379a2bd1eb2474bc869/642334d0d2e18d8670d46c78_Capture%20d%E2%80%99e%CC%81cran%202023-03-26%20a%CC%80%2016.37%202.png"
              className="w-full h-auto px-20"
              alt=""
              loading="lazy"
            />
          </div>
          <div className="flex flex-col justify-center">
            <div className="mb-4">
              <h2 className="text-2xl font-bold" id="banks">
                15 banks responsible for financing 240 projects
              </h2>
            </div>
            <p className="text-lg">
              Only 15 banks are responsible for the funding of 240 Carbon Bombs.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}



const OrdersOfMagnitudeSection = () => {
  return (
    <div className="py-16 bg-gray-100">
      <div className="container mx-auto px-4">
        <div className="px-8">
          <h2 className="text-2xl font-bold text-black">Orders of magnitude</h2>
          <div className="relative mt-8">
            <div
              className="slider-2 w-slider"
              data-autoplay="false"
              data-easing="ease"
              data-hide-arrows="false"
              data-disable-swipe="false"
              data-autoplay-limit="0"
              data-nav-spacing="3"
              data-duration="500"
              data-infinite="true"
              role="region"
              aria-label="carousel"
            >
              <div className="mask-2 w-slider-mask" id="w-slider-mask-0">
                <div className="slide-2 w-slide" aria-label="1 of 2" role="group">
                  <div className="testimonial_component">
                    <div className="div-block-2">
                      <img
                        src="https://uploads-ssl.webflow.com/64206379a2bd1eb2474bc869/6452167059d1f81bcf660ca2_bomb%20(1).png"
                        loading="lazy"
                        width="200"
                        height="200"
                        alt=""
                        className="image-15"
                      />
                      <div className="text-block-5">=</div>
                      <img
                        src="https://uploads-ssl.webflow.com/64206379a2bd1eb2474bc869/64519ea02f84b021a7a0c234_airplan.png"
                        loading="lazy"
                        width="200"
                        height="200"
                        alt=""
                        className="image-12"
                      />
                    </div>
                    <div className="div-block-4">
                      <div className="text-block-6">1 carbon bomb</div>
                      <div className="text-block-6">1.000.000.000 Paris-New York trips by plane</div>
                    </div>
                  </div>
                  <div className="testimonial-text_component">
                    <div className="testimonial_text">A carbon bomb emits over 1 billion tonnes of CO2 over its lifetime.</div>
                  </div>
                </div>
                <div className="slide-2 w-slide" aria-label="2 of 2" role="group" aria-hidden="true">
                  <div className="testimonial_component" aria-hidden="true">
                    <div aria-hidden="true" className="div-block-2" aria-hidden="true">
                      <img
                        src="https://uploads-ssl.webflow.com/64206379a2bd1eb2474bc869/6452167059d1f81bcf660ca2_bomb%20(1).png"
                        loading="lazy"
                        width="200"
                        height="200"
                        alt=""
                        className="image-16"
                        aria-hidden="true"
                      />
                      <div className="text-block-5" aria-hidden="true">=</div>
                      <img
                        src="https://uploads-ssl.webflow.com/64206379a2bd1eb2474bc869/64519f44c3fc40c4d1140d82_tree.png"
                        loading="lazy"
                        width="200"
                        height="200"
                        alt=""
                        className="image-14"
                        aria-hidden="true"
                      />
                    </div>
                    <div className="div-block-4" aria-hidden="true">
                      <div className="text-block-6" aria-hidden="true">1 carbon bomb</div>
                      <div className="text-block-6" aria-hidden="true">1.7 forest devastated</div>
                    </div>
                  </div>
                  <div className="testimonial-text_component" aria-hidden="true">
                    <div className="testimonial_text" aria-hidden="true">A carbon bomb emits over 1 billion tonnes of CO2 over its lifetime.</div>
                  </div>
                </div>
              </div>
              <div aria-live="off" aria-atomic="true" className="w-slider-aria-label" data-wf-ignore=""></div>
            </div>
            <div className="left-arrow w-slider-arrow-left" role="button" tabIndex="0" aria-label="previous slide">
              <div className="icon-3 w-icon-slider-left"></div>
            </div>
            <div className="right-arrow-2 w-slider-arrow-right" role="button" tabIndex="0" aria-label="next slide">
              <div className="icon-2 w-icon-slider-right"></div>
            </div>
            <div className="slide-nav-2 w-slider-nav w-round">
              <div className="w-slider-dot w-active" data-wf-ignore="" aria-label="Show slide 1 of 2" aria-pressed="true" role="button" tabIndex="0" style={{ marginLeft: '3px', marginRight: '3px' }}></div>
              <div className="w-slider-dot" data-wf-ignore="" aria-label="Show slide 2 of 2" aria-pressed="false" role="button" tabIndex="-1" style={{ marginLeft: '3px', marginRight: '3px' }}></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

const DataSection = () => {
  return (
    <div className="py-16 bg-gray-100">
      <div className="container mx-auto px-4">
        <div className="px-8">
          <div className="mb-8">
            <h2 className="text-2xl font-bold">Play with data</h2>
            <div>Our data is yours, please spread the message!</div>
          </div>
          <div className="mb-8">
            <h4 className="text-lg font-bold" id="map">Mapping carbon bombs worldwide</h4>
            <div className="tableauPlaceholder" style={{ position: 'relative', width: '100%', paddingBottom: '75%' }}>
              <iframe
                src="https://public.tableau.com/shared/7NRB8853X?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Fpublic.tableau.com%2F&:embed_code_version=3&:toolbar=yes&:animate_transition=yes&:display_static_image=no&:display_spinner=no&:display_overlay=yes&:display_count=yes&:language=fr-FR&publish=yes&:loadOrderID=0"
                className="tableauViz absolute inset-0 w-full h-full"
                style={{ border: 'none' }}
                allowFullScreen
              ></iframe>
            </div>
          </div>
          <div className="mb-8">
            <h4 className="text-lg font-bold" id="data">Most important carbon bombs</h4>
            <div className="tableauPlaceholder" style={{ position: 'relative', width: '100%', paddingBottom: '75%' }}>
              <iframe
                src="https://public.tableau.com/views/Lesbombescarbonesquiontleplusdmissions/Lesbombescarbonesquiontleplusdmissions?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Fpublic.tableau.com%2F&:embed_code_version=3&:tabs=no&:toolbar=yes&:animate_transition=yes&:display_static_image=no&:display_spinner=no&:display_overlay=yes&:display_count=yes&:language=fr-FR&publish=yes&:loadOrderID=1"
                className="tableauViz absolute inset-0 w-full h-full"
                style={{ border: 'none' }}
                allowFullScreen
              ></iframe>
            </div>
          </div>
          <div>
            <h4 className="text-lg font-bold">Companies with the highest emissions</h4>
            <div className="tableauPlaceholder" style={{ position: 'relative', width: '100%', paddingBottom: '75%' }}>
              <iframe
                src="https://public.tableau.com/views/Lesentreprisesquiontleplusdmissionsassocies/Entreprisesquiontleplusdeprojets?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Fpublic.tableau.com%2F&:embed_code_version=3&:tabs=no&:toolbar=yes&:animate_transition=yes&:display_static_image=no&:display_spinner=no&:display_overlay=yes&:display_count=yes&:language=fr-FR&publish=yes&:loadOrderID=2"
                className="tableauViz absolute inset-0 w-full h-full"
                style={{ border: 'none' }}
                allowFullScreen
              ></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}


const HomePage = () => {
  const [data, setData] = useState([]);
  const [dataFiltered, setDataFiltered] = useState([]);
  const [selectedCompanies, setSelectedCompanies] = useState([]);
  const [selectedCountries, setSelectedCountries] = useState([]);

  // const companyOptions = unique(data.map(item => item.company)).map(company => ({ value: company, label: company }));
  // const countryOptions = unique(data.map(item => item.country)).map(country => ({ value: country, label: country }));


  useEffect(() => {
    const fetchData = async () => {
      const res = await fetch('/api/data');
      const jsonData = await res.json();
      console.log(jsonData);
      setData(jsonData);
      setDataFiltered(jsonData);
    };

    fetchData();
  }, []);

  useEffect(() => {
    const filterData = () => {
      if (selectedCompanies.length || selectedCountries.length) {
        const filtered = data.filter(item =>
          (!selectedCompanies.length || item.Parent_company_source_GEM.some(company => selectedCompanies.find(option => option.value === company.company))) &&
          (!selectedCountries.length || selectedCountries.some(option => option.value === item.Country_source_CB))
        );
        setDataFiltered(filtered);
      } else {
        setDataFiltered(data);
      }
    }

    filterData();
  }, [selectedCompanies, selectedCountries]);


  return (
    <Layout>
      {/* <Seo templateTitle='Home' /> */}
      <Seo />

      <main>
        <div className="container mx-auto w-4/5 px-4">
          <div className="my-20">
            <div className="text-center">
              <div className="max-w-lg mx-auto">
                <div className="mb-4">
                  <h1 className="text-4xl font-bold text-center">Transparent data and <br /> visualization about carbon bombs</h1>
                </div>
                <p className="text-lg">CarbonBombs.org is a tool to follow the evolution of carbon bombs in the world.</p>
                <div className="mt-4">
                  <div className="text-center">
                    <a href="#data" className="py-2 px-4 bg-black text-white hover:bg-gray-800">Play with data</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* <SectionKPIs /> */}
          {/* <CarbonBombInfo /> */}
          <CarbonBombSection bombsData={data["bombs"]} />
          <TimeToActSection bombsData={data["bombs"]} />
          {/* <BanksSection /> */}
          {/* <OrdersOfMagnitudeSection /> */}
          <div className="flex justify-center my-5">
            <Select
              options={data.companies}
              className="mx-3 w-1/2"
              placeholder="Select a company..."
              isMulti
              onChange={setSelectedCompanies}
            />
            <Select
              options={data.countries}
              className="mx-3 w-1/2"
              placeholder="Select a country..."
              isMulti
              onChange={setSelectedCountries}
            />
          </div>
          <WorldMap bombsData={data["bombs"]} />
          {/* <DataSection /> */}

          {/* ... other sections ... */}

          <footer className="text-center py-10 mt-10 border-t">
            {/* <div className="flex justify-center space-x-4">
              <a href="#">Facebook</a>
              <a href="#">Instagram</a>
            </div> */}
            <p className="mt-4">&copy; 2023 CarbonBombs.org - All rights reserved</p>
          </footer>
        </div>
      </main>
    </Layout>
  );
}

export default HomePage;