const SectionKPIs = () => (
  <section className='my-10 bg-gray-100 py-10'>
    <div className='container mx-auto px-8'>
      <div className='max-w-3xl'>
        <h3 className='mb-2 text-2xl font-bold'>Carbon bombs at a glance</h3>
        <div className='text-gray-500'>Updated: 03/24/23</div>
      </div>
      <div className='-mx-4 mt-6 flex flex-wrap'>
        <div className='mb-4 w-full px-4 sm:w-1/2 lg:w-1/4'>
          <div className='flex h-full flex-col items-stretch rounded-lg bg-white p-6 shadow'>
            <h3 className='mb-1 text-5xl font-bold'>425</h3>
            <div className='font-bold'>CARBON BOMBS WORLDWIDE</div>
            <p className='mt-2'>
              425 fossil fuel projects around the world will generate more than
              1 gigatonne of CO2 emissions during their lifetime.
            </p>
          </div>
        </div>
        <div className='mb-4 w-full px-4 sm:w-1/2 lg:w-1/4'>
          <div className='flex h-full flex-col items-stretch rounded-lg bg-white p-6 shadow'>
            <h3 className='mb-1 text-5xl font-bold'>x2</h3>
            <div className='font-bold'>
              EXCEED 1.5°C CARBON BUDGET BY A FACTOR OF TWO
            </div>
            <p className='mt-2'>
              The cumulated volume of emissions generated by the 425 projects
              alone is twice larger than the 1.5°C carbon budget.
            </p>
          </div>
        </div>
        <div className='mb-4 w-full px-4 sm:w-1/2 lg:w-1/4'>
          <div className='flex h-full flex-col items-stretch rounded-lg bg-white p-6 shadow'>
            <h3 className='mb-1 text-5xl font-bold'>30</h3>
            <div className='font-bold'>MAJOR COMPANIES AND BANKS</div>
            <p className='mt-2'>are involved in the 425 projects.</p>
          </div>
        </div>
        <div className='mb-4 w-full px-4 sm:w-1/2 lg:w-1/4'>
          <div className='flex h-full flex-col items-stretch rounded-lg bg-white p-6 shadow'>
            <h3 className='mb-1 text-5xl font-bold'>40%</h3>
            <div className='font-bold'>HAVE NOT STARTED YET</div>
            <p className='mt-2'>
              40% of carbon bombs had not started extraction in 2020.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
);

export default SectionKPIs;
